/* eslint-disable @next/next/no-img-element */
import { useSession } from 'next-auth/react'

import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Home() {
  const { data: session, status } = useSession()
  // Show Link to Login page if NOT auth

  // console.log(session)
  // console.log(status)
  return (
    <div>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <Navbar />
        {session && <p>{session.user.email}</p>}
      </main>
      <footer></footer>
    </div>
  )
}
